# File cACSL/generation/Makefile
#
# Run
#  make wp
# to prove (may be very long),
#  make compile
# to produce the executable and
#  make test
# for testing.

wp:
	cd barray; make wp
	cd comb; make wp
	cd cperm; make wp
	cd derangement; make wp
	cd endobarray; make wp
	cd endoinj; make wp
	cd endorgf; make wp
	cd endosurj; make wp
	cd fact; make wp
	cd ffi; make wp
	cd injection; make wp
	cd injEndo; make wp
	cd invol; make wp
	cd pattern; make wp
	cd perm; make wp
	cd sorted; make wp
	cd sorted1; make wp
	cd sorted2; make wp
	cd surjection; make wp
	cd surjEndo; make wp

compile:
	cd barray; make compile
	cd comb; make compile
	cd cperm; make compile
	cd endobarray; make compile
	cd injEndo; make compile
	cd derangement; make compile
	cd injection; make compile
	cd endoinj; make compile
	cd endorgf; make compile
	cd surjection; make compile
	cd endosurj; make compile
	cd fact; make compile
	cd invol; make compile
	cd ffi; make compile
	cd perm; make compile
	cd sorted; make compile
	cd sorted1; make compile
	cd sorted2; make compile
	cd surjEndo; make compile

test: compile
	cd barray; make test
	cd comb; make test
	cd cperm; make test
	cd derangement; make test
	cd endobarray; make test
	cd endoinj; make test
	cd endorgf; make test
	cd endosurj; make test
	cd fact; make test
	cd ffi; make test
	cd injection; make test
	cd injEndo; make test
	cd invol; make test
	cd perm; make test
	cd sorted; make test
	cd sorted1; make test
	cd sorted2; make test
	cd surjection; make test
	cd surjEndo; make test

clean:
	cd barray; make clean
	cd comb; make clean
	cd cperm; make clean
	cd derangement; make clean
	cd endobarray; make clean
	cd endoinj; make clean
	cd endorgf; make clean
	cd endosurj; make clean
	cd fact; make clean
	cd ffi; make clean
	cd injection; make clean
	cd injEndo; make clean
	cd invol; make clean
	cd perm; make clean
	cd sorted; make clean
	cd sorted1; make clean
	cd sorted2; make clean
	cd surjection; make clean
	cd surjEndo; make clean